// Issue #79: 音源調整ツール用の波形ピークデータをビルドタイムに事前計算する。
//
// AUDIO_MANIFEST.sfxUrls の各 mp3 を Node 上で audio-decode → channelData[0]
// を WAVEFORM_BIN_COUNT 個のビンに分割し、各ビンの max(abs(sample)) を取得 →
// 全体最大値で正規化 → 固定精度で TS ファイルに書き出し。
//
// 出力ファイル src/lib/dev/waveform-peaks-data.ts は committed されている
// (dev mode で script 未実行でも import できるように)。
//
// Deterministic 出力なので input mp3 が変わらない限り git diff は出ない。

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import decode from "audio-decode";

import { AUDIO_MANIFEST } from "../src/lib/audio/manifest";
import {
  WAVEFORM_BIN_COUNT,
  WAVEFORM_FLOAT_PRECISION,
} from "../src/lib/dev/waveform-constants";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const PUBLIC_DIR = path.join(REPO_ROOT, "public");
const OUTPUT_PATH = path.join(REPO_ROOT, "src/lib/dev/waveform-peaks-data.ts");

interface PeaksAndDuration {
  peaks: number[];
  duration: number;
}

function extractPeaks(channel: Float32Array, bins: number): number[] {
  const samplesPerBin = Math.ceil(channel.length / bins);
  const peaks: number[] = [];
  let globalMax = 0;
  for (let i = 0; i < bins; i++) {
    const start = i * samplesPerBin;
    const end = Math.min(start + samplesPerBin, channel.length);
    let max = 0;
    for (let j = start; j < end; j++) {
      const v = Math.abs(channel[j]);
      if (v > max) max = v;
    }
    peaks.push(max);
    if (max > globalMax) globalMax = max;
  }
  // 全体最大で正規化 (静かな音でも視認できるように)
  const norm = globalMax > 0 ? globalMax : 1;
  return peaks.map((p) =>
    Number((p / norm).toFixed(WAVEFORM_FLOAT_PRECISION)),
  );
}

async function processFile(url: string): Promise<PeaksAndDuration | null> {
  const filePath = path.join(PUBLIC_DIR, url);
  try {
    const buffer = await readFile(filePath);
    const audio = await decode(
      buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength),
    );
    const channel = audio.channelData[0];
    const duration = Number((channel.length / audio.sampleRate).toFixed(WAVEFORM_FLOAT_PRECISION));
    const peaks = extractPeaks(channel, WAVEFORM_BIN_COUNT);
    return { peaks, duration };
  } catch (err) {
    console.warn(`[waveform] decode failed for ${url}:`, err instanceof Error ? err.message : err);
    return null;
  }
}

function formatTsOutput(
  results: Array<{ url: string; data: PeaksAndDuration | null }>,
): string {
  const peakLines = results
    .map(({ url, data }) => {
      const arr = data ? `[${data.peaks.join(",")}]` : `[]`;
      return `  ${JSON.stringify(url)}: ${arr},`;
    })
    .join("\n");

  const durationLines = results
    .map(({ url, data }) => `  ${JSON.stringify(url)}: ${data?.duration ?? 0},`)
    .join("\n");

  return `// AUTO-GENERATED by scripts/build-waveform-peaks.ts
// 編集禁止: pnpm build (または pnpm waveform:peaks) で再生成される。
// Deterministic 出力 (固定精度) のため input mp3 が変わらない限り diff 出ない。

export const WAVEFORM_PEAKS: Record<string, readonly number[]> = {
${peakLines}
};

export const WAVEFORM_DURATIONS: Record<string, number> = {
${durationLines}
};
`;
}

async function main(): Promise<void> {
  const urls = AUDIO_MANIFEST.sfxUrls;
  const results = await Promise.all(
    urls.map(async (url) => ({ url, data: await processFile(url) })),
  );
  const success = results.filter((r) => r.data !== null).length;
  const total = results.length;
  await writeFile(OUTPUT_PATH, formatTsOutput(results), "utf8");
  console.log(`[waveform] wrote ${OUTPUT_PATH} (${success}/${total} files decoded)`);
}

main().catch((err) => {
  console.error("[waveform] fatal:", err);
  process.exit(1);
});
